apiVersion: v1
kind: Service
metadata:
  name: media-service
spec:
  selector:
    app: media-service
  ports:
    - name: http
      port: {{ .Values.services.media_service.port }}
      targetPort: {{ .Values.services.media_service.port }}
  type: ClusterIP