apiVersion: v1
kind: Service
metadata:
  name: institute_learner-service
  namespace: default
spec:
  selector:
    app: institute_learner-service
  ports:
    - name: http
      port: { { .Values.services.student_service.port } }
      targetPort: { { .Values.services.student_service.port } }
  type: NodePort