apiVersion: apps/v1
kind: Deployment
metadata:
  name: institute_learner-service
  namespace: default
  labels:
    app: institute_learner-service
spec:
  replicas: { { .Values.replicaCount } }
  selector:
    matchLabels:
      app: institute_learner-service
  template:
    metadata:
      labels:
        app: institute_learner-service
    spec:
      containers:
        - name: institute_learner-service
          image: { { .Values.services.student_service.image.repository } }:{{ .Values.services.student_service.image.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "200m"
              memory: "450Mi"
            limits:
              cpu: "250m"
              memory: "600Mi"
          livenessProbe:
            httpGet:
              path: /institute_learner-service/actuator/health
              port: { { .Values.services.student_service.port } }
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          startupProbe:
            httpGet:
              path: /institute_learner-service/actuator/health
              port: { { .Values.services.student_service.port } }
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 30
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /institute_learner-service/actuator/health
              port: { { .Values.services.student_service.port } }
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          ports:
            - containerPort: { { .Values.services.student_service.port } }