apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-service
  ports:
    - name: http
      port: {{ .Values.services.student_service.port }}
      targetPort: {{ .Values.services.student_service.port }}
  type: ClusterIP